@echo off
echo Starting AI Interview Coach...

:: Start Backend
echo Starting Backend Server...
start "Backend Server" cmd /k "cd mockmate\server && npm run dev"

:: Start Frontend
echo Starting Frontend Application...
start "Frontend Application" cmd /k "cd mockmate && npm run dev"

echo Both services are starting in new windows...
